openapi: 3.0.3
info:
  title: Todo Application - Tasks API
  description: |
    Task management endpoints for the Todo application. All endpoints require JWT authentication.

    **Security Model**:
    - All endpoints require valid JWT token in Authorization header or cookie
    - user_id is extracted from JWT token (not from request body)
    - All operations are scoped to the authenticated user
    - Cross-user access returns 403 Forbidden

    **Base URL**: `http://localhost:8000` (development)
  version: 1.0.0
  contact:
    name: Todo App Development Team

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todo-app.com
    description: Production server (TBD)

tags:
  - name: Tasks
    description: Task management operations (CRUD)

paths:
  /api/tasks:
    get:
      tags:
        - Tasks
      summary: Get all tasks for authenticated user
      description: |
        Returns all tasks belonging to the authenticated user, ordered by creation date (newest first).

        **Security**: Only returns tasks where user_id matches the authenticated user's ID from JWT.
      operationId: getTasks
      security:
        - bearerAuth: []
        - cookieAuth: []
      responses:
        '200':
          description: Tasks retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              examples:
                with_tasks:
                  summary: User with tasks
                  value:
                    - id: 1
                      user_id: 1
                      title: Buy groceries
                      description: Milk, eggs, bread
                      is_completed: false
                      created_at: "2026-01-10T12:00:00Z"
                      updated_at: "2026-01-10T12:00:00Z"
                    - id: 2
                      user_id: 1
                      title: Finish project
                      description: null
                      is_completed: true
                      created_at: "2026-01-09T10:00:00Z"
                      updated_at: "2026-01-10T11:00:00Z"
                empty:
                  summary: User with no tasks
                  value: []
        '401':
          description: Not authenticated or token expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Tasks
      summary: Create a new task
      description: |
        Creates a new task for the authenticated user. The user_id is automatically set from the JWT token.

        **Note**: user_id in request body is ignored if provided. Always uses authenticated user's ID.
      operationId: createTask
      security:
        - bearerAuth: []
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
            examples:
              with_description:
                summary: Task with description
                value:
                  title: Buy groceries
                  description: Milk, eggs, bread
              without_description:
                summary: Task without description
                value:
                  title: Call dentist
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                success:
                  summary: Created task
                  value:
                    id: 1
                    user_id: 1
                    title: Buy groceries
                    description: Milk, eggs, bread
                    is_completed: false
                    created_at: "2026-01-10T12:00:00Z"
                    updated_at: "2026-01-10T12:00:00Z"
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                empty_title:
                  summary: Title is required
                  value:
                    message: Validation error
                    details:
                      title: ["Title is required"]
                title_too_long:
                  summary: Title exceeds max length
                  value:
                    message: Validation error
                    details:
                      title: ["Title must be at most 200 characters"]
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/tasks/{task_id}:
    get:
      tags:
        - Tasks
      summary: Get a specific task
      description: |
        Returns a single task by ID. Only returns the task if it belongs to the authenticated user.

        **Security**: Returns 403 if task belongs to a different user.
      operationId: getTask
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                success:
                  summary: Task details
                  value:
                    id: 1
                    user_id: 1
                    title: Buy groceries
                    description: Milk, eggs, bread
                    is_completed: false
                    created_at: "2026-01-10T12:00:00Z"
                    updated_at: "2026-01-10T12:00:00Z"
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                forbidden:
                  summary: Access denied
                  value:
                    message: You do not have permission to access this task
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                not_found:
                  summary: Task doesn't exist
                  value:
                    message: Task not found

    put:
      tags:
        - Tasks
      summary: Update a task
      description: |
        Updates an existing task. Only the provided fields are updated (partial update).

        **Security**: Only allows updating tasks that belong to the authenticated user.
      operationId: updateTask
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
            examples:
              update_title:
                summary: Update title only
                value:
                  title: Buy organic groceries
              update_completion:
                summary: Mark as complete
                value:
                  is_completed: true
              update_all:
                summary: Update all fields
                value:
                  title: Buy organic groceries
                  description: Milk, eggs, bread, vegetables
                  is_completed: false
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                success:
                  summary: Updated task
                  value:
                    id: 1
                    user_id: 1
                    title: Buy organic groceries
                    description: Milk, eggs, bread, vegetables
                    is_completed: false
                    created_at: "2026-01-10T12:00:00Z"
                    updated_at: "2026-01-10T13:00:00Z"
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - Tasks
      summary: Delete a task
      description: |
        Permanently deletes a task. This action cannot be undone.

        **Security**: Only allows deleting tasks that belong to the authenticated user.
      operationId: deleteTask
      security:
        - bearerAuth: []
        - cookieAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - is_completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int64
          description: Unique task identifier
          example: 1
        user_id:
          type: integer
          format: int64
          description: ID of the user who owns this task
          example: 1
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title/summary
          example: Buy groceries
        description:
          type: string
          maxLength: 1000
          nullable: true
          description: Optional detailed description
          example: Milk, eggs, bread
        is_completed:
          type: boolean
          description: Task completion status
          example: false
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
          example: "2026-01-10T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2026-01-10T12:00:00Z"

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title (required)
          example: Buy groceries
        description:
          type: string
          maxLength: 1000
          description: Optional task description
          example: Milk, eggs, bread

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Updated task title
          example: Buy organic groceries
        description:
          type: string
          maxLength: 1000
          nullable: true
          description: Updated task description (null to clear)
          example: Milk, eggs, bread, vegetables
        is_completed:
          type: boolean
          description: Updated completion status
          example: true

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Human-readable error message
          example: Validation error
        details:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Field-specific validation errors
          example:
            title: ["Title is required"]

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token in Authorization header (format: "Bearer <token>")
    cookieAuth:
      type: apiKey
      in: cookie
      name: auth-token
      description: JWT token stored in httpOnly cookie

security:
  - bearerAuth: []
  - cookieAuth: []
