openapi: 3.0.3
info:
  title: Todo App - Authentication API
  description: |
    Authentication endpoints provided by Better Auth for user registration and sign-in.
    Better Auth issues JWT tokens that are used by the FastAPI backend for authorization.
  version: 1.0.0
  contact:
    name: Todo App Team

servers:
  - url: http://localhost:3000
    description: Development server (Next.js with Better Auth)
  - url: https://app.example.com
    description: Production server

tags:
  - name: Authentication
    description: User registration, sign-in, and sign-out operations

paths:
  /api/auth/signup:
    post:
      tags:
        - Authentication
      summary: Register a new user account
      description: |
        Creates a new user account with email and password. Returns JWT token in httpOnly cookie.
        Corresponds to FR-001, FR-002, FR-003 from specification.
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address (must be unique)
                  example: user@example.com
                password:
                  type: string
                  format: password
                  minLength: 8
                  description: User's password (minimum 8 characters)
                  example: SecurePass123
      responses:
        '201':
          description: User account created successfully
          headers:
            Set-Cookie:
              description: JWT token in httpOnly cookie
              schema:
                type: string
                example: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; HttpOnly; Secure; SameSite=Strict
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: User ID
                        example: 1
                      email:
                        type: string
                        format: email
                        description: User's email
                        example: user@example.com
                      createdAt:
                        type: string
                        format: date-time
                        description: Account creation timestamp
                        example: "2026-01-10T12:00:00Z"
        '400':
          description: Invalid request (email format invalid, password too short)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid email format"
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Email already exists"

  /api/auth/signin:
    post:
      tags:
        - Authentication
      summary: Sign in to existing account
      description: |
        Authenticates user with email and password. Returns JWT token in httpOnly cookie.
        Corresponds to FR-004, FR-005 from specification.
      operationId: signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: user@example.com
                password:
                  type: string
                  format: password
                  description: User's password
                  example: SecurePass123
      responses:
        '200':
          description: Authentication successful
          headers:
            Set-Cookie:
              description: JWT token in httpOnly cookie
              schema:
                type: string
                example: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; HttpOnly; Secure; SameSite=Strict
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: User ID
                        example: 1
                      email:
                        type: string
                        format: email
                        description: User's email
                        example: user@example.com
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid email or password"

  /api/auth/signout:
    post:
      tags:
        - Authentication
      summary: Sign out of current session
      description: |
        Invalidates the current JWT token by clearing the httpOnly cookie.
        Corresponds to FR-007 from specification.
      operationId: signout
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Sign out successful
          headers:
            Set-Cookie:
              description: Clears auth token cookie
              schema:
                type: string
                example: auth-token=; HttpOnly; Secure; SameSite=Strict; Max-Age=0
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Signed out successfully"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: auth-token
      description: JWT token stored in httpOnly cookie

  schemas:
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid request"

security:
  - cookieAuth: []
