openapi: 3.0.3
info:
  title: Todo App - Tasks API
  description: |
    Task management endpoints provided by FastAPI backend.
    All endpoints require JWT authentication via Authorization header.
    All operations are scoped to the authenticated user (strict user isolation).
  version: 1.0.0
  contact:
    name: Todo App Team

servers:
  - url: http://localhost:8000
    description: Development server (FastAPI)
  - url: https://api.example.com
    description: Production server

tags:
  - name: Tasks
    description: CRUD operations for user tasks
  - name: Health
    description: Service health check

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check endpoint
      description: Returns service status (no authentication required)
      operationId: healthCheck
      security: []
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2026-01-10T12:00:00Z"

  /api/tasks:
    get:
      tags:
        - Tasks
      summary: Get all tasks for authenticated user
      description: |
        Returns all tasks belonging to the authenticated user.
        Corresponds to FR-010 from specification.
        User isolation: Only returns tasks where user_id matches authenticated user.
      operationId: getTasks
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      tags:
        - Tasks
      summary: Create a new task
      description: |
        Creates a new task for the authenticated user.
        Corresponds to FR-008, FR-009 from specification.
        User isolation: user_id is automatically set from JWT token.
      operationId: createTask
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/ValidationError'

  /api/tasks/{taskId}:
    get:
      tags:
        - Tasks
      summary: Get a specific task
      description: |
        Returns a single task by ID.
        User isolation: Returns 404 if task doesn't exist or belongs to different user.
      operationId: getTask
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags:
        - Tasks
      summary: Update a task
      description: |
        Updates title and/or description of an existing task.
        Corresponds to FR-014 from specification.
        User isolation: Returns 404 if task doesn't exist or belongs to different user.
      operationId: updateTask
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      tags:
        - Tasks
      summary: Delete a task
      description: |
        Permanently deletes a task.
        Corresponds to FR-015, FR-016 from specification.
        User isolation: Returns 404 if task doesn't exist or belongs to different user.
      operationId: deleteTask
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/tasks/{taskId}/complete:
    patch:
      tags:
        - Tasks
      summary: Toggle task completion status
      description: |
        Toggles the is_completed status of a task.
        Corresponds to FR-012 from specification.
        User isolation: Returns 404 if task doesn't exist or belongs to different user.
      operationId: toggleTaskCompletion
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token issued by Better Auth (extract from httpOnly cookie on frontend)

  parameters:
    TaskId:
      name: taskId
      in: path
      required: true
      description: Unique task identifier
      schema:
        type: integer
        example: 1

  schemas:
    Task:
      type: object
      required:
        - id
        - userId
        - title
        - isCompleted
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          description: Unique task identifier
          example: 1
        userId:
          type: integer
          description: ID of the user who owns this task
          example: 1
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          maxLength: 2000
          description: Optional task description
          example: "Milk, eggs, bread"
        isCompleted:
          type: boolean
          description: Task completion status
          example: false
        createdAt:
          type: string
          format: date-time
          description: Task creation timestamp
          example: "2026-01-10T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last modification timestamp
          example: "2026-01-10T12:30:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title (required)
          example: "Buy groceries"
        description:
          type: string
          maxLength: 2000
          description: Optional task description
          example: "Milk, eggs, bread"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Updated task title
          example: "Buy organic groceries"
        description:
          type: string
          nullable: true
          maxLength: 2000
          description: Updated task description
          example: "Organic milk, free-range eggs, whole grain bread"

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Invalid request"

    ValidationError:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
                description: Location of validation error
                example: ["body", "title"]
              msg:
                type: string
                description: Error message
                example: "field required"
              type:
                type: string
                description: Error type
                example: "value_error.missing"

  responses:
    Unauthorized:
      description: Authentication required or token invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Could not validate credentials"

    Forbidden:
      description: User does not have permission to access this resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Access forbidden"

    NotFound:
      description: Task not found or does not belong to authenticated user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Task not found"

    BadRequest:
      description: Invalid request data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Invalid request"

    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'

security:
  - bearerAuth: []
